### ISSUE TITLE
App is not starting

### ISSUE THREAD

**Issue by horodnicdragos** [zeit/next-plugins#121] opened 2018-03-29 10:37 UTC
Greetings!

I tried to use next with the preact plugin but for some reason it says this on run dev:

```
 ERROR  Failed to compile with 9 errors                                                                                                                                    13:21:02

These dependencies were not found:

* react in ./node_modules/next/dist/client/index.js, ./node_modules/next/dist/lib/error-debug.js and 6 others
* react-dom in ./node_modules/next/dist/client/index.js

To install them, you can run: npm install --save react react-dom
(node:3620) DeprecationWarning: Module.chunks: Use Module.forEachChunk/mapChunks/getNumberOfChunks/isInChunk/addChunk/removeChunk instead
> Ready on http://localhost:3000
```

This is what I have in my package.json, I am using node v9.3.0 and npm 5.6.0:
```
{
  "name": "nextjs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@zeit/next-preact": "0.0.6",
    "next": "^5.1.0",
    "preact": "^8.2.7",
    "preact-compat": "^3.18.0",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```

I have created the next.config.js, server.js and an index page and I don't know if there is something I might have missed. Does anyone have a clue?

**Comment by timneutkens** [comment] 2018-03-29 11:38
Duplicate of https://github.com/zeit/next-plugins/issues/119

**Closed by timneutkens** 2018-03-29 11:38 UTC
