### ISSUE TITLE
Can't navigate to dynamic pages using <Link>

### ISSUE THREAD

**Issue by rasnick** [zeit/next-plugins#527] opened 2019-08-27 04:43 UTC
# Bug report

## Describe the bug

Using @zeit/next-css 1.0.1 for importing CSS files, Links aren't working. Applies in all scenarios: dev, build-start and export.

## To Reproduce

1) Clone and install repo: https://github.com/rasnick/dobuy
2) Uncomment "import './app.css'" on file /pages/_app.js
3) run dev, start or export

## Expected behavior

Clicking the links should go to their respective dynamic pages.

## System information

- OS: Ubuntu 18.04.2
- Browser (if applies): Firefox
- Version of Next.js: 9.0.4
- Version of @zeit/next-css: 1.0.1

## Additional context

Importing an empty CSS file inside_app.js file is a workaround.

```javascript
import React from 'react'
import App from 'next/app'

// comment this empty import and the issue is reproduced
import './app.css'

class MyApp extends App {

  render() {
    const { Component, pageProps } = this.props
    return <Component {...pageProps} />
  }
}

export default MyApp
```

**Comment by timneutkens** [comment] 2019-08-27 08:16
Duplicate of https://github.com/zeit/next-plugins/issues/282

**Closed by timneutkens** 2019-08-27 08:16 UTC
