### ISSUE TITLE
Next redirect `Router.push` from A to B takes forever when page B imports css that A doesn't have

### ISSUE THREAD

**Issue by jtomaszewski** [zeit/next-plugins#512] opened 2019-08-06 10:28 UTC
Our case:

- next 9.0.3 with @zeit/next-css 1.0.1
- serving app using local next server (with custom express js middleware)
- page A loads no css
- page B loads css file (`react-dates/lib/css/_datepicker.css`)

Problem:

If on page A we call `Router.push('/b')` in order to navigate to page B, nothing happens.

However, if we directly go to /b , and then navigate to /a and then to /b using the `Router.push()`, then it works.

After we moved the CSS import to be global (so it is imported by both page A and page B), the problem vanished.

So, seems like, while page A wanted to load page B, it was waiting indefinitely for the B's css to be loaded, and that's why nothing had happened? Hard to say.

Unfortunately, we can't give any demo of that for now, but at least we're making the bug report - I'm curious if somebody else also has met similar issue. (Ourselves, for now we'll go with workaround of moving the css import to be global for all the pages.)

**Comment by timneutkens** [comment] 2019-08-06 13:58
Duplicate of #282

**Closed by timneutkens** 2019-08-06 13:58 UTC
