### ISSUE TITLE
Typescript 2.9.2 typed tagged template not compiling correctly

### ISSUE THREAD

**Issue by geelen** [zeit/next-plugins#214] opened 2018-07-09 05:46 UTC
Since Typescript 2.9.2, you can now have type declarations between template tag functions and their template literals, like this in styled components:

```ts
interface FrameProps {
  background: string
}

export const Frame = styled.div<FrameProps>`
  background: url("${props => props.background}") no-repeat 50% 50% / cover;
  width: 100vw;
  min-height: 100vh;
  overflow: hidden;
`
```

This code typechecks & compiles fine with TS 2.9.2, and is able to typecheck the `props` interpolation automatically through Webstorm, which is p neat. But when I run that in Next (either in dev or build & start) I get the following error:

```
ReferenceError: FrameProps is not defined
```

The compiled code looks like this:

```js
var Frame = __WEBPACK_IMPORTED_MODULE_0_styled_components___default.a.div < FrameProps > "\n  background: url(\"".concat(function (props) {
  return props.background;
}, "\") no-repeat 50% 50% / cover;\n  width: 100vw;\n  min-height: 100vh;\n  overflow: hidden;\n");
```

Without the type hint between `div` and the template string, the compiled output looks like this:

```js
var Frame = __WEBPACK_IMPORTED_MODULE_0_styled_components___default.a.div(_templateObject2, function (props) {
  return props.background;
});
```

So clearly the type annotation isn't being removed, which means Babel isn't compiling it as a tagged template literal any more, but rather an inequality expression using a now-erased interface `TypeProps`

Trying to force the babel build to use `^7.0.0-beta.52` everywhere gives me this error:

```
Module build failed: Error: [BABEL] Frame.tsx: .overrides is not allowed in preset options
```

Pretty new to TypeScript and Next and this stuff is pretty fresh out the kitchen so I may be off track here, but it feels like something changed between `.42` and `.52` that Next is incompatible with? Once that incompatibility is resolved, it might be just a matter of pointing `next-typescript` at the latest point releases?

Hope this helps someone, this is a really neat language feature for Styled Components & Typescript users, so would love to see it supported by default in Next-Typescript

**Comment by thomhos** [comment] 2018-07-09 07:41
next-typescript uses babel to transpile ts to js (effectively removing the annotations etc). Babel-typescript doesn't support all features of typescript so it could very well be that this isn't supported considering it's such a new feature.

If you want to have full TS support you'd have to add the ts-loader yourself instead of using the with-typescript plugin (just look at an older version of with-typescript plugin).

**Comment by geelen** [comment] 2018-07-09 08:19
Ahh that's really helpful, thanks. I hadn't grokked that there were two systems at play here.

**Comment by kachkaev** [comment] 2018-08-20 21:14
I guess this issue is a duplicate of https://github.com/zeit/next-plugins/issues/203. Looks like it can be closed anyway because tagged template literals finally work! (see [details](https://github.com/zeit/next-plugins/issues/203#issuecomment-414465052))

**Closed** 2018-08-21 01:54 UTC

**Comment by timneutkens** [comment] 2018-08-21 21:14
Lets update to rc2 and then wait for the stable release, it's going to be out this week. 

https://github.com/babel/babel/releases/tag/v7.0.0-rc.2
