### ISSUE TITLE
CSS Loader Invalid Options Error

### ISSUE THREAD

**Issue by Tyguy160** [zeit/next-plugins#392] opened 2019-02-02 17:34 UTC
When loading in a CSS file from `node_modules` using the `next.config.js` file [here](https://github.com/zeit/next-plugins/tree/master/packages/next-css#without-css-modules), the following error is generated on compile:

```
./node_modules/react-table/react-table.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties
```

In referencing the suggestion from @truonghoangphuc [here](https://github.com/webpack-contrib/css-loader/issues/863#issuecomment-450625939), I commented out `minimize: !dev,` in `css-loader-config.js` in `node_modules/@zeit/next-css/css-loader-config.js`

```
const cssLoader = {
    loader: isServer ? 'css-loader/locals' : 'css-loader',
    options: Object.assign(
      {},
      {
        modules: cssModules,
        //minimize: !dev,
        sourceMap: dev,
        importLoaders: loaders.length + (postcssLoader ? 1 : 0),
      },
      cssLoaderOptions
    ),
  };
```

I've confirmed that commenting that line out makes CSS loading work again and the errors go away.

**Comment by luankefei** [comment] 2019-02-14 06:48
+1.  this error happend from css-loader 2.0.0

**Comment by popuguytheparrot** [comment] 2019-02-19 08:03
dont update to css-loader to v2. Inside using v1

**Comment by chuyik** [comment] 2019-02-20 10:27
Link related PR https://github.com/zeit/next-plugins/pull/350 to this issue.

**Comment by evilebottnawi** [comment] 2019-03-15 11:30
cssLoaderOptions contains something wrong, can you do `console.log(cssLoaderOptions)`?

**Comment by sergaunt** [comment] 2019-03-16 13:33
Also got this error while using `withCss`. Error disappeared after downgrading `css-loader`.

**Comment by evilebottnawi** [comment] 2019-03-16 14:22
@sergaunt please create minimum reproducible test repo, thanks!

**Comment by szpasztor** [comment] 2019-03-16 16:10
I also got this error while using `withCss`. Commenting out `minimize` and downgrading `css-loader` to `v1.0.1` both solved the issue.

**Comment by efleurine** [comment] 2019-03-22 16:26
@szpasztor if you comment out `minimze` then you won't have minize file in the end right?

**Comment by marcusstenbeck** [comment] 2019-03-23 06:47
This workaround removes the `minimize` option from all `css-loader` entries in the Webpack config. I hope someone finds it useful.

```js
// next.config.js
const withCSS = require('@zeit/next-css');

function HACK_removeMinimizeOptionFromCssLoaders(config) {
  console.warn(
    'HACK: Removing `minimize` option from `css-loader` entries in Webpack config',
  );
  config.module.rules.forEach(rule => {
    if (Array.isArray(rule.use)) {
      rule.use.forEach(u => {
        if (u.loader === 'css-loader' && u.options) {
          delete u.options.minimize;
        }
      });
    }
  });
}

module.exports = withCSS({
  webpack(config) {
    HACK_removeMinimizeOptionFromCssLoaders(config);
    return config;
  },
});
```

Using `next@8.0.3` and `@zeit/next-css@1.0.1`.

**Comment by mbavio** [comment] 2019-03-30 05:41
I can confirm that hack is not needed with `@zeit/next-css@canary`.

**Comment by Aid19801** [comment] 2019-04-05 13:07
i used the hack. sorted it right out. cheers.

**Comment by sanzhardanybayev** [comment] 2019-04-11 22:06
I don't even have **minimize** option but still get the same error 😕

**Comment by sanzhardanybayev** [comment] 2019-04-11 22:21
Installing packages via **yarn** solved the problem. What the heck? 🤯

**Comment by evilebottnawi** [comment] 2019-04-11 22:21
npm cache

**Comment by sanzhardanybayev** [comment] 2019-04-11 22:23
@evilebottnawi that was a fresh install. So I don't think that the problem is in **cache**

**Comment by jnv** [comment] 2019-08-15 11:38
I ran into the same issue with `next-less`, upgrading to canary version also fixed it (as it depends on canary version of `next-css`). However, currently there seems to be a mismatch between versions and npm tag for canary versions of CSS-related packages as pointed out here: https://github.com/zeit/next-plugins/commit/12cd9d28905b63a1b90848f3e494dc3fb7465224#commitcomment-33755090.
So installing `@zeit/next-css@canary` gives you `0.2.1-canary.4` while the actual version of next canary release is `1.0.2-canary.2`. I _think_ the contents of packages should be the same, just pay attention if the package versions get corrected in the future.

**Comment by KnightYoshi** [comment] 2019-09-10 01:22
@jnv Even when installing `@zeit/next-css@canary` it still complains
> [ error ] ../node_modules/antd/dist/antd.less
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.

Using
```
"@zeit/next-css": "^0.2.1-canary.4",
"@zeit/next-less": "^0.3.1-canary.4",
```

I'm trying to get Ant Design styles written in Less to be correctly imported, but to no avail. 😫

**Comment by goranefbl** [comment] 2019-09-17 07:26
Same is with next-sass, loader needs fixing or updating.

**Comment by KnightYoshi** [comment] 2019-09-17 12:33
Yep, I tried `next-sass` last night.

**Comment by goranefbl** [comment] 2019-09-18 06:26
The solution from @marcusstenbeck  works, but I could not find minimize option inside css-loader in node_modules, or it is inside some other package...

**Comment by andezzat** [comment] 2019-10-02 01:16
I had this issue...
Upgrading to the latest `next` (9.0.7) introduced it..
Then upgrading to the latest `@zeit/next-css` (1.0.1) fixed it!

**Comment by KnightYoshi** [comment] 2019-10-02 01:37
@andezzat Share your config/setup, because using the "latest" versions does not fix anything.

I've tried with all three packages and get the same result. You're getting different results than the rest of us.
```json
"@zeit/next-css": "^1.0.1",
"@zeit/next-less": "^1.0.1",
"@zeit/next-sass": "^1.0.1",
...
"next": "^9.0.7",
```

```js
// next.config.js
const withCSS = require('@zeit/next-css')
module.exports = withCSS()
```

```
./assets/styles.css
ValidationError: Invalid options object. CSS Loader has been initialised using an options object that does not match the API schema.
 - options has an unknown property 'minimize'. These properties are valid:
   object { url?, import?, modules?, sourceMap?, importLoaders?, localsConvention?, onlyLocals? }
```

**Comment by andezzat** [comment] 2019-10-02 02:14
@KnightYoshi Apologies, you're right!
I ran `yarn add something` to get a package, and suddenly it came back.

I'm pretty sure it only realised it needs `css-loader@3.2.0` the second pass around.
And now it's erroring again :)

I'm going to investigate why this `minimize` option isn't being dropped.

**Comment by andezzat** [comment] 2019-10-02 02:53
Ok... so here's what I know so far
I hope this is helpful to @zeit staff.

1. I'm on `next@9.0.5`
2. I update to `next@9.0.7` & get the `minimize` `css-loader` error
3. I update to `@zeit/next-css@1.0.2-canary.2` which fixes the issue as it removes the `minimize` flag from the `options` (despite using `css-loader@1.0.0`, which has shouldn't error for this!)

What I reckon is causing this issue in `next@9.0.7` is the addition of the `css-loader@3.2.0` & its usage in the webpack config's `module.rules`:
https://github.com/zeit/next.js/blob/2c7b4d8aaac475f81de21c0e9cb40fdea1a7a178/packages/next/build/webpack-config.ts#L339

That's as far as I have time to look into this...

**Comment by wulfmann** [comment] 2019-10-02 21:59
next @9.0.6 does not have the issue either.

**Comment by KnightYoshi** [comment] 2019-10-02 22:33
@wulfmann 9.0.5—9.0.7 all have the same issue. I started on 9.0.5 and upgraded to 9.0.6 and then 9.0.7. All of which generate the same _CSS loader invalid config_  issue.

**Comment by andezzat** [comment] 2019-10-02 22:54
@wulfmann & @KnightYoshi 

As per my dissection comment above: please try installing `@zeit/next-css@1.0.2-canary.2`
Can confirm (tested multiple times), this fixed the issue for me!

**Comment by atombender** [comment] 2019-10-02 23:18
@andezzat Still failing for me.

**Comment by rlech** [comment] 2019-10-02 23:24
I can confirm using `@zeit/next-css@1.0.2-canary.2` is working for me

**Comment by KnightYoshi** [comment] 2019-10-03 02:14
Thanks @andezzat 

Using `@zeit/next-css@1.0.2-canary.2` works, same for `@zeit/next-less@1.0.2-canary.2`, and I assume the Sass one will as well (haven't tested, yet).

**Comment by atombender** [comment] 2019-10-03 04:01
@andezzat Correction, I didn't upgrade `@zeit/next-sass` to the same canary release. After upgrading that, I no longer get the error — as long as I have `css-loader@1.0.0`.

If I upgrade to `css-loader@3.2`, everything breaks:

```
Module not found: Can't resolve 'css-loader/locals'
```

No idea where this comes from, since there's no stack trace. It's odd, since my code doesn't reference `css-loader` at all, and Next.js already depends on 3.2. But presumably, if Next's WebPack config references `css-loader` by _string_, it will probably get it from my dependencies, not Next.js's?

**Comment by hackneycrypto** [comment] 2019-10-03 15:57
> This workaround removes the `minimize` option from all `css-loader` entries in the Webpack config. I hope someone finds it useful.
> 
> ```js
> // next.config.js
> const withCSS = require('@zeit/next-css');
> 
> function HACK_removeMinimizeOptionFromCssLoaders(config) {
>   console.warn(
>     'HACK: Removing `minimize` option from `css-loader` entries in Webpack config',
>   );
>   config.module.rules.forEach(rule => {
>     if (Array.isArray(rule.use)) {
>       rule.use.forEach(u => {
>         if (u.loader === 'css-loader' && u.options) {
>           delete u.options.minimize;
>         }
>       });
>     }
>   });
> }
> 
> module.exports = withCSS({
>   webpack(config) {
>     HACK_removeMinimizeOptionFromCssLoaders(config);
>     return config;
>   },
> });
> ```
> 
> Using `next@8.0.3` and `@zeit/next-css@1.0.1`.

Installed Hack - worked for me

**Comment by Timer** [comment] 2019-10-04 00:40
This has been fixed in `next@^9.0.8-canary.4` and newer!

**Closed by Timer** 2019-10-04 00:40 UTC

**Comment by andezzat** [comment] 2019-10-05 00:07
@Timer sure!

But shouldn't breaking changes like these be part of stable releases so people don't run around in circles like they did in this thread trying to figure out what's broken?

**Comment by orourkea2017** [comment] 2019-10-05 10:31
@andezzat is right. Next 9.0.7 is broken. It needs to be fixed.

**Comment by timneutkens** [comment] 2019-10-05 11:02
@orourkea2017 

> This has been fixed in next@^9.0.8-canary.4 and newer!

It already is fixed. Just pending stable release. Please try it out.

**Comment by orourkea2017** [comment] 2019-10-05 11:10
A timeframe @timneutkens?? A bugfix is no use in beta.

**Comment by timneutkens** [comment] 2019-10-05 11:11
The way you're communicating is kind of weird. But we don't release on weekends and no one communicated back that it works so we were waiting a bit to see if other issues pop up.

**Comment by orourkea2017** [comment] 2019-10-05 11:23
Okay, thank you. I apologise if I come across as strange - that was not my intention, although I know I am blunt at times. Sorry. I also did not realise it was a weekend - I am in Australia, and while we are on a weekend, I always think that everyone else is miles behind us time-wise. Again, sorry.

I take it we can expect this to be stable in a few days. Thank you, much appreciated.
