### ISSUE TITLE
next-sass seems to be breaking Router.push

### ISSUE THREAD

**Issue by jp26jp** [zeit/next-plugins#311] opened 2018-10-17 11:39 UTC
[Here's an example repo](https://github.com/jp26jp/next-sass-bug).

## How to reproduce:
1. Run `npm i`
2. Run `npm run dev`
3. Go to http://localhost:3000
4. Sign in. You should be able to sign in but you will get stuck on the http://localhost:3000/auth/signed-in page because the `Router.push("/")` call inside the `./pages/auth/signed-in.js` file will fail to redirect the page.

## How to fix:
1. Comment out the first import in the `./components/Header.js` file as well as in the `./components/NotAuthorized.js` file. Doing this will prevent the `next-sass` plugin from processing the scss file.
2. With these lines commented out, try logging in again and you will be successfully redirected to the root page.

**Comment by timneutkens** [comment] 2018-10-17 11:43
Duplicate of #282

**Closed by timneutkens** 2018-10-17 11:43 UTC
