### ISSUE TITLE
next-css: Routing to another page doesn't load CSS in development mode

### ISSUE THREAD

**Issue by Splendith** [zeit/next-plugins#263] opened 2018-09-16 19:49 UTC
## Describe the bug
When using Next.js with next-css plugin (canary version). Routing to another page doesn't load CSS styles, you will need to refresh the page to get the styles.

## To Reproduce
1. Clone https://github.com/Splendith/next.js-test (on master branch)
2. Run `npm i` and then `npm run dev`
3. Visit `http://localhost:3000`, you will see index page with big red "HelloIndexPage" text
4. Click 'Test Page' link
5. You will see the non-styled "HelloTestPage" text
6. Refresh page and you will see big orange "HelloTestPage" text

## System information
- Version of next: 7.0.0-canary.18
- Version of @zeit/next-css: 0.2.1-canary.2
- Version of react: 16.5.0
- Web browser: Google Chrome / Firefox

## Additional context
- It does not happen in production deployment (`npm run build` -> `npm run start`).
- next 6.0 and @zeit/next-css 0.2.0 also happen, you can reproduce by checkout next_v6 branch and follow the same above steps

**Comment by timneutkens** [comment] 2018-09-16 20:09
This is fixed in `next@canary` + `@zeit/next-css@canary` as far as I know.

**Comment by GerardVee** [comment] 2018-09-23 08:16
Any updates? I'm also having the same issue under similar circumstances.

**Comment by calmburst** [comment] 2018-09-28 06:45
Looking forward for a fix :)

**Comment by kylemh** [comment] 2018-10-05 18:08
This is a dupe of https://github.com/zeit/next-plugins/issues/282 and #282 contains a workaround with extra discussion. Should this issue be closed, and the other left open?

**Comment by code-coder** [comment] 2018-10-23 06:09
same problem. 
The file _styles.chunk.css_ in _.next/static/css/_ has changed when i use _Link_ or _Router.push()_ to another page, but in the browser it stays the same from the first time loaded.

**Comment by timneutkens** [comment] 2018-10-23 10:44
Duplicate of #282

**Closed by timneutkens** 2018-10-23 10:44 UTC

**Comment by drydenwilliams** [comment] 2019-11-21 12:24
I just found that I wasn't doing using `<Link />` correctly so on any sub pages my CSS wasn't loading. 

I had to change: 

```
 <Link
      key={EventID}
      href={`/event/${eventSlug}/${EventID}`}
      as={`/event/${eventSlug}/${EventID}`}
    >
```

to this: 

```
 <Link
      key={EventID}
      href={`/event/[name]/[id]`}
      as={`/event/${eventSlug}/${EventID}`}
    >
```

Noting that the `href` prop is now the path of the page in the pages folder and `as` is the URL to show in URL bar of the browser.

**Comment by chornos13** [comment] 2020-05-03 01:28
I just made some modification from this issue https://github.com/zeit/next-plugins/issues/282

and I got this working on mine

`// import App from 'next/app'
import React from 'react'
import Router from 'next/router';
function MyApp({ Component, pageProps }) {
  return  <Component {...pageProps} />
}

if (process.env.NODE_ENV !== 'production') {
  **Router.events.on('routeChangeComplete', () => {
    const els = document.querySelectorAll('link[href*="/_next/static/css/styles.chunk.css"]');
    const timestamp = new Date().valueOf();
    for (let i = 0; i < els.length; i++) {
      if(els[i].rel === 'stylesheet') {
        els[i].href = '/_next/static/css/styles.chunk.css?v=' + timestamp;
        break;
      }
    }
  })**
}

export default MyApp
`

what you need is just blocked text

**Comment by chornos13** [comment] 2020-05-03 01:33
I just made some modification from this issue https://github.com/zeit/next-plugins/issues/282

and I got this working for me

```
_app.js

// import App from 'next/app'
import React from 'react'
import Router from 'next/router';
function MyApp({ Component, pageProps }) {
  return  <Component {...pageProps} />
}

if (process.env.NODE_ENV !== 'production') {
  Router.events.on('routeChangeComplete', () => {
    const els = document.querySelectorAll('link[href*="/_next/static/css/styles.chunk.css"]');
    const timestamp = new Date().valueOf();
    for (let i = 0; i < els.length; i++) {
      if(els[i].rel === 'stylesheet') {
        els[i].href = '/_next/static/css/styles.chunk.css?v=' + timestamp;
        break;
      }
    }
  })
}

export default MyApp

```

**Comment by raindecastro** [comment] 2020-06-14 00:31
@chornos13 Thanks for the workaround! Can confirm that this is working

**Comment by CyberCowboy404** [comment] 2020-06-22 19:07
Had same problem.
When I've removed `<Head>` component from pages where I'm using it for setting title, the problem is gone and styles applying for every page.
But how can I reuse it for different pages with meta tags and different titles?

**Comment by thotho19** [comment] 2020-06-25 21:59
use cdn

**Comment by faeghe-hajiabadi** [comment] 2020-07-23 12:15
I have same problem but in mine I can see css styles in page I access into by Link from other pages but when I want to access page with url I do not see any css style. has anyone any idea?

**Comment by dmtx97** [comment] 2020-07-27 17:59
I am having a similar issue. Does the CSS load for you after a refresh? That is my issue.

**Comment by MartinYounghoonKim** [comment] 2020-08-25 15:02
any update ?

**Comment by dmtx97** [comment] 2020-08-25 19:14
@MartinYounghoonKim As far as I know I haven't found a fix. Styling works perfectly in production mode though.

**Comment by insivika** [comment] 2020-08-29 01:12
Having this issue as well :/

**Comment by Jhenri-silva** [comment] 2020-10-11 16:34
What I did to solve this problem is to make a direct on root index. Simple as that I think. Then, you could redirect to whatever the page you wanna that breaks, and the css will load just correctly (just if you did a refresh)

`// import { AmplifyAuthenticator } from '@aws-amplify/ui-react'
import { Amplify, API, Auth, withSSRContext } from 'aws-amplify'
import { useRouter } from 'next/router'
import awsExports from '../src/aws-exports'
import { useEffect } from 'react'
// import { createPost } from '../src/graphql/mutations'
// import { listPosts } from '../src/graphql/queries'
import styles from '../styles/Home.module.css'

Amplify.configure({ ...awsExports, ssr: true })



const RootPage = ({ props }) => {
  console.log('props', props)
  const router = useRouter()

  useEffect(() => {
    router.push('/ask')
  })
  return null
}

export async function getStaticProps(ctx) {
  if (ctx.req) {
    ctx.res.writeHead(302, { Location: '/ask' })
    ctx.res.end()
  }
  return { props: { ok: 'ok' } }
}

export default RootPage`

**Comment by Jhenri-silva** [comment] 2020-10-11 16:34
What I did to solve this problem is to make a direct on root index. Simple as that I think. Then, you could redirect to whatever the page you wanna that breaks, and the css will load just correctly (just if you did a refresh)

```
// import { AmplifyAuthenticator } from '@aws-amplify/ui-react'
import { Amplify, API, Auth, withSSRContext } from 'aws-amplify'
import { useRouter } from 'next/router'
import awsExports from '../src/aws-exports'
import { useEffect } from 'react'
// import { createPost } from '../src/graphql/mutations'
// import { listPosts } from '../src/graphql/queries'
import styles from '../styles/Home.module.css'

Amplify.configure({ ...awsExports, ssr: true })

const RootPage = ({ props }) => {
console.log('props', props)
const router = useRouter()

useEffect(() => {
router.push('/ask')
})
return null
}

export async function getStaticProps(ctx) {
if (ctx.req) {
ctx.res.writeHead(302, { Location: '/ask' })
ctx.res.end()
}
return { props: { ok: 'ok' } }
}

export default RootPage
```

**Comment by AlexandraKlein** [comment] 2020-12-27 16:09
> I just made some modification from this issue #282
> 
> and I got this working for me
> 
> fix memory leak (update jun 17 20)
> 
> ```
> //_app.js
> 
> // import App from 'next/app'
> import React from 'react'
> import Router from 'next/router';
> import * as PropTypes from 'prop-types'
> 
> 
> class MyApp extends React.Component {
>   cacheURL = []
>   handleLoadStyle = (url) => {
>     if (this.cacheURL.includes(url)) return
>     const els = document.querySelectorAll(
>       'link[href*="/_next/static/css/styles.chunk.css"]')
>     const timestamp = new Date().valueOf()
>     for (let i = 0; i < els.length; i++) {
>       if (els[i].rel === 'stylesheet') {
>         els[i].href = '/_next/static/css/styles.chunk.css?v=' + timestamp
>         console.log('Style loaded')
>         this.cacheURL.push(url)
>         break
>       }
>     }
>   }
> 
>   componentDidMount () {
>     if (process.env.NODE_ENV !== 'production') {
>       // prevent duplication listener
>       Router.events.on('routeChangeComplete', this.handleLoadStyle)
>     }
>   }
> 
>   componentWillUnmount () {
>     if (process.env.NODE_ENV !== 'production') {
>       Router.events.off('routeChangeComplete', this.handleLoadStyle)
>     }
>   }
> 
>   render () {
>     let { Component, pageProps } = this.props
> 
> 
>     return <Component {...pageProps} />
>   }
> }
> 
> MyApp.propTypes = {
>   Component: PropTypes.any,
>   pageProps: PropTypes.any
> }
> 
> 
> export default MyApp
> ```
> 
> or you can convert it to hooks for simplification

Modified from @chornos13 using hooks:
