### ISSUE TITLE
CSS and <Link> tags don't work when a page is missing a style import declaration

### ISSUE THREAD

**Issue by amoeba** [zeit/next-plugins#418] opened 2019-03-02 19:41 UTC
This issue was baffling me for a while but I managed to reproduce it (repo below) and find a fix.

**Behavior:** In an app with pages other than `index.js`, if you open the app in a new browser tab to one of those other pages (e.g., `object.js`), styles don't render as they did on `index.js` and `Link` elements aren't clickable.

**Steps to reproduce:**

```sh
git clone https://github.com/amoeba/nextjs-broken-links
cd nextjs-broken-links
npm install
npm run dev
```

Then:

- Open http://localhost:3000/object/test in a web browser
- Notice the links Index and Test don't work. Also notice the styles aren't rendering as expected

**Steps to fix:**

Add missing `import` statement for the CSS in https://github.com/amoeba/nextjs-broken-links/blob/master/pages/object.js as in `index.js` (`import "../style.scss"`).

It makes sense to me that I should import my styles in each page (or put it in the JSX _or_ in a Layout) but the confusing behavior was that breakage of the `Link` elements with no error messages. Does this sound like a bug or maybe a quality of life improvement for either `next-sass` or `next-css`?

**Comment by timneutkens** [comment] 2019-03-02 19:50
I think this is a duplicate of https://github.com/zeit/next-plugins/issues/282

**Comment by amoeba** [comment] 2019-03-02 20:00
Does sound like a duplicate. Sorry about that. Feel free to close.

**Comment by timneutkens** [comment] 2019-03-02 20:05
🙌

**Closed by timneutkens** 2019-03-02 20:05 UTC
